### ISSUE TITLE
Demo page only accepts 2 character long hex salts

### ISSUE THREAD

**Issue by jeorgen** [ricmoo/scrypt-js#12]
Hi,
The demo page at http://ricmoo.github.io/scrypt-js/ has this test for a valid hex salt:

`if (!value.match(/^[0-9A-F][0-9A-F]$/i)) {
                        throw new Error(field + ': invalid hex string');
                    }`

`/^[0-9A-F][0-9A-F]$/i` matches exactly two characters. Instead one could have:

`/^[0-9A-F]{64}$/i`

**Comment by TotalTechGeek** [comment]
I realize this issue is over a year old, but I thought I'd reply to it for anyone else that might find this project.

The third-party client side "buffer" module that the author utilizes does not accept hex strings that aren't divisible by two ([offending line of code here](https://github.com/ricmoo/scrypt-js/blob/8ed332cd30f287edfa9ae075845252c244d490a1/thirdparty/buffer.js#L447)).

**Comment by ricmoo** [comment]
This has been fixed. Sorry for the long delay.

Let me know if there are any more problems.

Thanks! :)
