### ISSUE TITLE
Providing a sync version

### ISSUE THREAD

**Issue by alcuadrado** [ricmoo/scrypt-js#20]
Hi @ricmoo,

I'm opening this issue because I'm interested in using this library instead of [`scryptsy`](https://www.npmjs.com/package/scryptsy), as that one uses `crypto-browserify` in the browser, and that implies a huge bundle that normally doesn't get tree-shaken and doesn't seem to work with Rollup.

The problem is that some projects, like [`ethereumjs-wallet` here](https://github.com/ethereumjs/ethereumjs-wallet/blob/master/src/index.ts#L316), use the sync version of `scryptsy`. This is not ideal, but can't be changed without introducing a breaking change.

I'm wondering if you are open to adding a sync version to this library.

Thanks!

**Comment by ricmoo** [comment]
Yes, this is something I’ve thought about adding. It shouldn’t be too hard, since it can just call the co-routine component without using a setImmediate.

As an aside, if you use my `ethers` library (or the beta v5 sub-package, `@ethersproject/json-wallets`) to decrypt an Ethereum Wallet, you get the async version of wallet decrypting, so you can update a progress bar in the UI. :)

**Comment by alcuadrado** [comment]
> if you use my `ethers` library (or the beta v5 sub-package, `@ethersproject/json-wallets`)

Thanks for pointing me to that package. Looks very useful!

**Comment by ricmoo** [comment]
There is now a sync version available in this library, and the async version returns a Promise instead of archaic callbacks.

Please try it out and let me know if you have any problems. :)
